# Generated by Django 4.2.9 on 2026-03-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
